# Site settings
title: AJ
email: ajvarshneya@gmail.com
description: >
  description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ajvarshneya.com" # the base hostname & protocol for your site
github_username:  ajvarshneya

# Build settings
markdown: kramdown
